Some aggregation are sum, product, median, minimum, maximum, quantiles .. etc

## Summing the Values in an array

In [1]:
import numpy as np
rng = np.random.default_rng()
L = rng.random(100)
sum(L)

np.float64(55.83828876108536)

In [2]:
# syntax is similar to Numpy's sum function
np.sum(L)


np.float64(55.838288761085366)

However it execute the operation in compiled code, Numpy version operation is computed much more quickly

In [3]:
big_array = rng.random(100000)
%timeit sum(big_array)
%timeit np.sum(big_array)

21.9 ms ± 1.39 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
72.2 µs ± 2.99 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## Maximum and Minimum

In [4]:
min(big_array), max(big_array)

(np.float64(9.399029400336545e-07), np.float64(0.9999914329296649))

In [5]:
np.min(big_array), np.max(big_array)


(np.float64(9.399029400336545e-07), np.float64(0.9999914329296649))

In [6]:
%timeit min(big_array)
%timeit np.min(big_array)

7.4 ms ± 97.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
40 µs ± 8.64 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
# shorter syntax
print(big_array.min(), big_array.max(), big_array.sum())

9.399029400336545e-07 0.9999914329296649 50100.29236689174


## Multidimensional Aggregates

In [9]:
M = rng.integers(0,10,(3,4))
print(M)

[[4 3 0 6]
 [5 1 6 7]
 [4 6 4 3]]


In [10]:
M.sum()

np.int64(49)

In [11]:
M.min(axis=0)

array([4, 1, 0, 3])

In [12]:
M.max(axis=1)

array([6, 7, 6])

## Other Aggregation Functions

The following table provides a list of useful aggregation functions available in NumPy:

|Function name    |   NaN-safe version| Description                                   |
|-----------------|-------------------|-----------------------------------------------|
| `np.sum`        | `np.nansum`       | Compute sum of elements                       |
| `np.prod`       | `np.nanprod`      | Compute product of elements                   |
| `np.mean`       | `np.nanmean`      | Compute mean of elements                      |
| `np.std`        | `np.nanstd`       | Compute standard deviation                    |
| `np.var`        | `np.nanvar`       | Compute variance                              |
| `np.min`        | `np.nanmin`       | Find minimum value                            |
| `np.max`        | `np.nanmax`       | Find maximum value                            |
| `np.argmin`     | `np.nanargmin`    | Find index of minimum value                   |
| `np.argmax`     | `np.nanargmax`    | Find index of maximum value                   |
| `np.median`     | `np.nanmedian`    | Compute median of elements                    |
| `np.percentile` | `np.nanpercentile`| Compute rank-based statistics of elements     |
| `np.any`        | N/A               | Evaluate whether any elements are true        |
| `np.all`        | N/A               | Evaluate whether all elements are true        |