## Numpy Array attributes



In [3]:
import numpy as np
rng = np.random.default_rng(seed=1701) # seed for reproduciblity

x1 = rng.integers(10, size=6) # ONE DIMENSIONAL
x2 = rng.integers(10, size=(3,4)) # Two dimensional
x3 = rng.integers(10, size=(3,4,5)) # Three dimensional

print("x3 dimensions", x3.ndim)
print("x3 shape", x3.shape)
print("x3 size", x3.size)
print("dtype:   ", x3.dtype)
print("itemsize:", x3.itemsize)

x3 dimensions 3
x3 shape (3, 4, 5)
x3 size 60
dtype:    int64
itemsize: 8


**ndim** : the number of dimensions

**shape**: the size of each dimension

**size**: the total size of array

**dtype**: type of each element

**itemsize**: size in byte of one element in array

## Array Indexing

In [4]:
x1

array([9, 4, 0, 3, 8, 6])

In [5]:
x1[0]

np.int64(9)

To index from end use negative indices

In [6]:
x1[-2]

np.int64(8)

In multidimensional array, items can be accessed using a comma-separated (row, column)

In [7]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]])

In [8]:
x2[0,0]

np.int64(3)

Values can also be modified using any of the preceding index notation

In [9]:
x2[0,0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

Numpy arrays have a fixed type, if we insert a floating point value into an integer array, value will be truncated

## Array Slicing

syntax: x[start:stop:step]

### One Dimensional

In [10]:
x1

array([9, 4, 0, 3, 8, 6])

In [12]:
x1[:3] # first three element

array([9, 4, 0])

In [13]:
x1[3:] # elements after index 3

array([3, 8, 6])

In [14]:
x1[1:4] # middle subarray

array([4, 0, 3])

In [15]:
x1[::2] # every second element

array([9, 0, 8])

In [16]:
x1[1::2] # every second element, starting at index 1

array([4, 3, 6])

### Multidimensional Subarrays

In [17]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]])

In [18]:
x2[:2, :3] # first two rows and three column


array([[12,  1,  3],
       [ 4,  0,  2]])

In [19]:
x2[::-1, ::-1] # all rows and column reversed

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]])

In [20]:
x2[:, 0] # first column of x2

array([12,  4,  0])

## Subarrays as No-Copy Views

Numpy array slices are returned as **views** rather than **copies** of the array data

In [21]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [22]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


In [23]:
x2_sub[0,0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [24]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## Copies of Arrays

**copy()** is used to copy

In [25]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [26]:
x2_sub_copy[0,0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [27]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


## Reshaping of Arrays

In [28]:
grid = np.arange(1, 10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**NOTE :** for this to work, the size of this initial array must match the size of the reshaped array, and in most cases the reshape method will return a no copy view of initial array

In [29]:
x = np.array([1,2,3])
x.reshape((1,3)) # row vector via reshape

array([[1, 2, 3]])

In [31]:
x.reshape((3,1)) # column vector via reshape

array([[1],
       [2],
       [3]])

A convenient shorthand is to use **np.newaxis**

In [32]:
x[np.newaxis, :] # row vector via newaxis

array([[1, 2, 3]])

In [33]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Concatenation of Arrays

Contenation of two arrays in numpy by using **np.concatenate**, **np.vstack**, **np.hstack**

In [34]:
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [35]:
# Two dimensional
grid = np.array([[5,6,4],
                [8,7,6]])
np.concatenate([grid, grid])

array([[5, 6, 4],
       [8, 7, 6],
       [5, 6, 4],
       [8, 7, 6]])

In [36]:
# concatenate along the second axis
np.concatenate([grid, grid], axis=1)


array([[5, 6, 4, 5, 6, 4],
       [8, 7, 6, 8, 7, 6]])

For working with array using mixed dimensions , use **np.vstack** (vertical stack), **np.hstack** (horizontal stack)

In [37]:
np.vstack([x, grid])

array([[1, 2, 3],
       [5, 6, 4],
       [8, 7, 6]])

In [38]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 5,  6,  4, 99],
       [ 8,  7,  6, 99]])

For higher dimensional arrays, **np.dstack** will stack arrays along third axis

## Splitting of Arrays

In [39]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1,x2, x3)

[1 2 3] [99 99] [3 2 1]


**N** split points leads to **N + 1** SUBARRAYS

In [40]:
grid = np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [42]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [43]:
left, right = np,np.hsplit(grid, [2])
print(left)
print(right)

<module 'numpy' from '/usr/local/lib/python3.12/dist-packages/numpy/__init__.py'>
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]
