## A single integer in python actually contain four spices
**ob_refcnt** : a refrence count that helps python silently handle memory allocation and deallocation

**ob_type**: which encodes the type of the variable

**ob_size**: which specifies the size of the following data mebers

**ob_digit**: which contains the actual integer value that we expect the python variable to represent

In [2]:
L = list(range(10))
L
type(L[0])
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

we can create heterogeneous list because of python dynamic typing

In [3]:
L3 = [True, "2", 3.0, 5]
[type(item)for item in L3]

[bool, str, float, int]

## Fixed type Arrays in Python

python offer several different options for storing data in efficient, fixed type data buffers

In [4]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here, **' i '**  is a type code indicating the contents are integers

## Creating Arrays from Python lists

**np.array** is use to create arrays from python lists

unlike Python lists , Numpy arrays can only contain data of the same type. If the data type not matched Numpy will upcast them according to its type promotion rule

In [6]:
import numpy as np
p = np.array([1,2,1,3,4])
q = np.array([3.15,2,5,6])
q


array([3.15, 2.  , 5.  , 6.  ])

we can use explicitly data type by using of **dtype**

In [7]:
np.array([1,2,3,4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

Unlike python list, which are one dimensioanl sequence, Numpy array can be multidimensional

In [8]:
np.array([range(i, i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating array from scratch

In [9]:
## create a 3 * 5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# Create an array of five values evenly spaced b/w 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# create an array of 3 * 3 uniformly distributed
np.random.random((3,3))

array([[0.05854744, 0.44772952, 0.89398789],
       [0.66907436, 0.90663308, 0.14995778],
       [0.1282033 , 0.24877905, 0.67105202]])

In [13]:
# create a 3 * 3 array of randomm number in the interval [0,10)
np.random.randint(0,10,(3,3))

array([[7, 9, 0],
       [7, 7, 3],
       [4, 3, 0]])

In [15]:
# create an identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])