In [1]:
import numpy as np

In [2]:
name = ['alice', 'bob', 'cathy', 'Doug']
age = [24, 45, 37, 19]
wight = [55.0, 85.5, 68.0, 61.5]

In [3]:
x = np.zeros(4, dtype=int)

In [4]:
# use compound data type for structured arrays

data = np.zeros(4, dtype={'names':('name', 'age', 'weight'),
                          'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


**U10** translate to "unicode string of maximum length 10"

**i4** translate to "4byte = 32 bits integer"

**f8** translate to "8 byte float"

In [5]:
data['name'] = name
data['age'] = age
data['weight'] = wight
print(data)

[('alice', 24, 55. ) ('bob', 45, 85.5) ('cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [7]:
# Get all the name
data['name']

array(['alice', 'bob', 'cathy', 'Doug'], dtype='<U10')

In [8]:
# Get first row data
data[0]

np.void(('alice', 24, 55.0), dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [10]:
# get names where age is under 30
data[data['age'] < 30]['name']

array(['alice', 'Doug'], dtype='<U10')

## Structured array creation

In [11]:
np.dtype({'names':('name', 'age', 'weight'),
         'formats':('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [12]:
# numerical type can be specified using python types or numpy dtype

np.dtype({'names':('name', 'age', 'weight'),
         'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [13]:
# compound type can also be specified as a list of tuples
np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f8')])

dtype([('name', 'S10'), ('age', '<i4'), ('weight', '<f8')])

## More Advanced Compound Types

In [14]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3,3))])
x = np.zeros(1, dtype=tp)
print(x[0])
print(x['mat'][0])

(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
