## The Slowness of Loops
Python's default implementation (known as CPython) does some operations very slowly . This is partly due to dynamic, interpreted nature of the language; types are flexible so sequence of operations cannot be compiled down to efficient machine code like c

In [1]:
import numpy as np
rng = np.random.default_rng(seed=1701)

def compute_reciprocals(values):
  output = np.empty(len(values))
  for i in range(len(values)):
    output[i] = 1.0 / values[i]
  return output

values = rng.integers(1, 10, size=5)
print(compute_reciprocals(values))

[0.11111111 0.25       1.         0.33333333 0.125     ]


This might feel normal but for large data its taking some seconds to execute


In [2]:
big_array = compute_reciprocals(rng.integers(1, 100, size=1000000))
%timeit compute_reciprocals(big_array)

370 ms ± 126 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


Vectorized operation in Numpy are implemented via **ufuncs** , whose main function is to execute repeated operations on values in Numpy arrays.

In [3]:
np.arange(5) / np.arange(1, 6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

**ufuncs** operation can also work in multidimensional arrays

In [4]:
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

## Numpy's Ufuncs

Ufuncs exists in two flavors: **unary ufuncs** (operates on single input)  
**binary ufuncs** (which operates on two inputs)

## Array Arithmetic

In [5]:
x = np.arange(4)

print("x     =", x)
print("x+5   =", x+5)
print("x-5   =", x-5)
print("x*5   =", x*5)
print("x/5   =", x/5)
print("x//5  =", x//5)
print("x**5  =", x**5)
print("x%5   =", x%5)
print("-x    =", -x)

x     = [0 1 2 3]
x+5   = [5 6 7 8]
x-5   = [-5 -4 -3 -2]
x*5   = [ 0  5 10 15]
x/5   = [0.  0.2 0.4 0.6]
x//5  = [0 0 0 0]
x**5  = [  0   1  32 243]
x%5   = [0 1 2 3]
-x    = [ 0 -1 -2 -3]


## Arithmetic operation implemented in Numpy

+ (+ = np.add)
+ (- = np.subtract)
+ (* = np.multiply)
+ (/ = np.divide)
+ (// = np.floor_divide)
+ (- = np.negative)
+ (** = np.power)
+ (% = np.mod)


## Absolute Value

In [6]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [7]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [8]:
np.abs(x)

array([2, 1, 0, 1, 2])

## Trigonometric Functions

In [9]:
theta = np.linspace(0, np.pi, 3)

In [10]:
print("theta:   ", theta)
print("sin(theta):   ", np.sin(theta))
print("cos(theta):   ", np.cos(theta))
print("tan(theta):   ", np.tan(theta))

theta:    [0.         1.57079633 3.14159265]
sin(theta):    [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta):    [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta):    [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [11]:
# for inverse use arc prefix
x = [-1, 0, 1]
print("x         = ", x)
print("arcsin(x) = ", np.arcsin(x))
print("arccos(x) = ", np.arccos(x))
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


## Exponents and Logarithms

In [13]:
x = [1,2,3]
print("x   =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3., x))

x   = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3.  9. 27.]


In [15]:
# inverse of exponential is logarithm
x = [1,2,4,10]
print("x        =", x)
print("ln(x)    =", np.log(x))
print("log2(x)  =", np.log2(x))
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


## Specialized ufuncs

If you want to compute some obsecure mathematical function chances that it is implemented in **scipy.special**

In [16]:
from scipy import special

In [17]:
# Gamma function(generalized factorials) and related functions
x = [1, 5 ,10]
print("gamma(x)     =", special.gamma(x))
print("ln|gamma(x)| =", special.gammaln(x))
print("beta(x,2)    =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x,2)    = [0.5        0.03333333 0.00909091]


In [18]:
# error function (integral of Gaussian)
x = np.array([0,0.3,0.7,1.0])
print("erf(x)  =", special.erf(x))
print("erfc(x) =", special.erfc(x))
print("erfinv(x) =", special.erfinv(x))

erf(x)  = [0.         0.32862676 0.67780119 0.84270079]
erfc(x) = [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) = [0.         0.27246271 0.73286908        inf]


## Specifying Output

For large calculations, it is sometime useful to specify the array where the result of the calculation will be stored

In [19]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


## Aggregations

For binary ufuncs, aggregations can be computed directly from the object.

A **reduce** repeatedly applies a given operation to the elements of an array until only a single result remains

In [20]:
# reduce on the add ufunc return sum of all elements in the array
x = np.arange(1,6)
np.add.reduce(x)

np.int64(15)

In [21]:
# reduce on multiply result in product of array element
np.multiply.reduce(x)

np.int64(120)

we can store all intermediate result using **accumulate**

In [22]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [23]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

## Outer Products

any ufunc can compute the output of all pairs of two different inputs using **outer** method

In [24]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])